# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protopassprofile',
            name='storage_key',
            field=models.TextField(default=12345678901234567890123456789012),
            preserve_default=False,
        ),
    ]
